version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - my-network

  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Senha@123
      MYSQL_USER: docker
      MYSQL_PASSWORD: Senha@123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3308
    depends_on:
      - naming-server
    networks:
      - my-network

  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Senha@123
      MYSQL_USER: docker
      MYSQL_PASSWORD: Senha@123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    depends_on:
      - naming-server
    networks:
      - my-network

  naming-server:
    image: jonatanery/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - my-network

  api-gateway:
    image: jonatanery/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - my-network

  cambio-service:
    image: jonatanery/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Senha@123
      SPRING.FLYWAY.URL: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: Senha@123
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio_db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge