on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      # Build and package each microservice
      - name: Build Eureka Naming Server Container Image
        working-directory: ./Dockerizing/naming-server
        run: mvn spring-boot:build-image -DskipTests

      - name: Build API Gateway Container Image
        working-directory: ./Dockerizing/api-gateway
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Cambio Microservice Jar
        working-directory: ./Dockerizing/cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice Jar
        working-directory: ./Dockerizing/book-service
        run: mvn clean package -DskipTests

      # Ensure JAR files are present before Docker Compose build
      - name: List files in cambio-service target
        working-directory: ./Dockerizing/cambio-service
        run: ls -l target

      - name: List files in book-service target
        working-directory: ./Dockerizing/book-service
        run: ls -l target

      - name: Docker Compose Build
        working-directory: ./Dockerizing
        run: docker-compose build
